apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consul-servers.fullname" . }}-config
data:
  server.hcl: |
    datacenter      = "{{ .Values.datacenter }}"
    data_dir        = "/consul/data"
    log_level       = "INFO"

    # --- Server flags ---
    server           = true
    bootstrap_expect = {{ .Values.replicaCount }}
    performance {
      raft_multiplier = 1
    }

    # --- Networking ---
    bind_addr      = "0.0.0.0"
    advertise_addr = "${POD_IP}"

    retry_join = [
      "provider=k8s label_selector=\"app=consul,component=server\" namespace={{ .Release.Namespace }}"
    ]

    # TLS, ACLs, gossip encryption can be appended here later