apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul-servers.fullname" . }}-lb
  labels:
    app: consul
    component: server
    exposure: external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local          # preserves client IPs
  selector:
    app: consul
    component: server
  ports:
    # ---------- Raft & gossip ----------
    - name: rpc
      port: 8300
      targetPort: rpc          # TCP 8300 (Raft)
      protocol: TCP

    - name: gossip-tcp
      port: 8301
      targetPort: serf         # TCP 8301 (LAN gossip)
      protocol: TCP

    - name: gossip-udp
      port: 8301
      targetPort: serf-udp     # UDP 8301 (LAN gossip)
      protocol: UDP

    # ---------- WAN gossip (optional; safe to leave) ----------
    - name: wan-tcp
      port: 8302
      targetPort: wan
      protocol: TCP
    - name: wan-udp
      port: 8302
      targetPort: wan-udp
      protocol: UDP

    # ---------- HTTP / HTTPS API & UI ----------
    - name: http
      port: 8500               # plaintext UI / API
      targetPort: http
      protocol: TCP
    - name: https
      port: 8501               # TLS-terminated variant (enable later)
      targetPort: http
      protocol: TCP

    # ---------- DNS ----------
    - name: dns
      port: 8600
      targetPort: dns
      protocol: UDP